name: aibodes
description: Aibodes - A real estate app with Tinder-like swiping functionality
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_swiper_view: ^1.1.8
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  
  # Real Estate API Integration
  dio: ^5.3.2                    # Advanced HTTP client for API calls
  json_annotation: ^4.8.1        # JSON serialization annotations
  
  # Maps & Location Services
  google_maps_flutter: ^2.5.0    # Google Maps integration
  geolocator: ^10.1.0            # Location services
  geocoding: ^2.1.1              # Address geocoding
  
  # Advanced UI Components
  photo_view: ^0.14.0            # Photo gallery with zoom
  carousel_slider: ^4.2.1        # Image carousels
  shimmer: ^3.0.0                # Loading animations
  
  # Data Management
  hive: ^2.2.3                   # Local database
  hive_flutter: ^1.1.0           # Hive Flutter integration
  connectivity_plus: ^5.0.2      # Network connectivity
  
  # Utilities
  intl: ^0.18.1                  # Internationalization
  url_launcher: ^6.2.1           # Launch external URLs
  permission_handler: ^11.0.1    # Permission management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7           # Code generation runner
  json_serializable: ^6.7.1      # JSON serialization generator
  hive_generator: ^2.0.1         # Hive code generator

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
